# Base SIEM Configuration

# Core Settings
environment: base
debug: false
log_level: INFO

# Agent Configuration
agent_collection_interval: 60
max_queue_size: 1000

# Database Configuration
database:
  host: localhost
  port: 5432
  name: siem_db
  user: siem_user
  pool_size: 10

# Security Settings
security:
  jwt_algorithm: HS256
  jwt_expiration_minutes: 30
  password_min_length: 12

# Collectors
collectors:
  - system_logs
  - network_traffic
  - security_events

# Threat Intelligence Configuration
threat_intelligence:
  enabled: true
  ml_models:
    default_path: E:\SIEM\SIEM\models\default_model.pkl
    anomaly_detection:
      contamination: 0.1
      random_seed: 42

  feeds:
    - name: OTX
      type: otx
      enabled: false
      api_key: ""
    
    - name: VirusTotal
      type: virustotal
      enabled: false
      api_key: ""
    
    - name: MISP
      type: misp
      enabled: false
      url: ""
      api_key: ""

  # Threat Detection Thresholds
  thresholds:
    low_risk: 0.3
    medium_risk: 0.6
    high_risk: 0.9

# Logging Configuration
logging:
  handlers:
    - type: console
      level: INFO
    - type: file
      filename: logs/siem_main.log
      level: DEBUG
      max_bytes: 10485760  # 10 MB
      backup_count: 5
    - type: error_file
      filename: logs/siem_error.log
      level: ERROR
      max_bytes: 5242880  # 5 MB
      backup_count: 3
