# Enterprise SIEM Configuration Template
# Copy this file to config.yaml and modify according to your needs

system:
  name: "Enterprise SIEM"
  environment: "production"  # production, staging, development
  debug: false
  log_level: "INFO"
  timezone: "UTC"

security:
  encryption_key: ""  # Set a strong encryption key
  jwt_secret: ""     # Set a strong JWT secret
  session_timeout: 3600  # seconds
  password_policy:
    min_length: 12
    require_special: true
    require_numbers: true
    require_uppercase: true
    max_age_days: 90

database:
  type: "sqlite"  # sqlite, postgresql
  path: "data/siem.db"  # for sqlite
  # postgresql settings (if using postgresql)
  host: "localhost"
  port: 5432
  name: "siem"
  user: ""
  password: ""
  pool_size: 20
  max_overflow: 10

incident_response:
  queue_size: 10000
  worker_threads: 4
  auto_remediation: true
  notification:
    email:
      enabled: true
      smtp_server: "smtp.gmail.com"
      smtp_port: 587
      username: ""
      password: ""
      from_address: ""
      to_addresses: []
    slack:
      enabled: true
      webhook_url: ""
      channel: "#security-alerts"
  severity_levels:
    critical: 1
    high: 2
    medium: 3
    low: 4

compliance:
  frameworks:
    - "PCI-DSS"
    - "HIPAA"
    - "GDPR"
    - "ISO27001"
  scan_interval: 3600  # seconds
  report_retention: 90  # days
  auto_remediation: false
  notification:
    threshold_severity: "high"

vulnerability_scanner:
  scan_types:
    - "port"
    - "service"
    - "vulnerability"
    - "web"
  port_ranges: "1-1024,1433,3306,3389,5432,27017"
  concurrent_scans: 5
  timeout: 300  # seconds
  web_scan:
    crawl_depth: 3
    exclude_paths: []
    auth:
      enabled: false
      method: "basic"
      credentials: {}
  reporting:
    min_severity: "medium"
    formats:
      - "json"
      - "html"
      - "pdf"

network_monitoring:
  device_discovery:
    enabled: true
    interval: 300  # seconds
    methods:
      - "active"
      - "passive"
  asset_tracking:
    enabled: true
    history_retention: 90  # days
  behavioral_analysis:
    enabled: true
    baseline_period: 7  # days
  alerts:
    new_device: true
    os_change: true
    service_change: true

threat_detection:
  ml_models:
    anomaly_detection:
      enabled: true
      algorithm: "isolation_forest"
      training_interval: 86400  # seconds
    classification:
      enabled: true
      algorithm: "random_forest"
      retraining_threshold: 0.1  # accuracy drop
  feature_analysis:
    enabled: true
    importance_threshold: 0.05
  threat_intel:
    enabled: true
    sources:
      - "alienvault"
      - "virustotal"
    update_interval: 3600  # seconds

api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  rate_limit:
    enabled: true
    requests_per_minute: 60
  cors:
    enabled: true
    allow_origins: ["*"]
    allow_methods: ["*"]
    allow_headers: ["*"]

logging:
  file:
    enabled: true
    path: "logs/siem.log"
    max_size: 100  # MB
    backup_count: 10
  syslog:
    enabled: false
    host: "localhost"
    port: 514
  elasticsearch:
    enabled: false
    host: "localhost"
    port: 9200
    index_prefix: "siem-logs"

monitoring:
  metrics:
    enabled: true
    prometheus:
      enabled: true
      port: 9090
    statsd:
      enabled: false
      host: "localhost"
      port: 8125
  health_check:
    enabled: true
    interval: 60  # seconds
    endpoints:
      - "/"
      - "/api/health"

storage:
  type: "local"  # local, s3
  local:
    path: "data/"
  s3:
    bucket: ""
    region: ""
    access_key: ""
    secret_key: ""
  retention:
    logs: 90  # days
    reports: 365  # days
    scans: 180  # days
