# Password Mutation Rules
# These rules are used by the password auditor to generate variations of dictionary words

- name: "Basic Capitalization"
  capitalize: true
  description: "Capitalize the first letter"

- name: "Full Uppercase"
  uppercase: true
  description: "Convert entire word to uppercase"

- name: "Common Number Append"
  append: "123"
  description: "Append common number sequence"

- name: "Year Append"
  append: "2024"
  description: "Append current year"

- name: "Special Character Append"
  append: "!"
  description: "Append exclamation mark"

- name: "Special Character Prepend"
  prepend: "@"
  description: "Prepend at symbol"

- name: "Basic Leet Speak"
  leetspeak:
    a: "4"
    e: "3"
    i: "1"
    o: "0"
    s: "5"
  description: "Basic letter to number substitutions"

- name: "Advanced Leet Speak"
  leetspeak:
    a: "@"
    b: "8"
    c: "("
    e: "3"
    g: "6"
    h: "#"
    i: "!"
    l: "1"
    o: "0"
    s: "$"
    t: "7"
    z: "2"
  description: "Advanced character substitutions"

- name: "Number Suffix"
  append: ["1", "12", "123", "1234", "12345"]
  description: "Common numerical suffixes"

- name: "Special Character Suffix"
  append: ["!", "@", "#", "$", "%", "&", "*"]
  description: "Common special character suffixes"

- name: "Year Variations"
  append: ["2024", "2023", "2022", "2021", "2020"]
  description: "Common year suffixes"

- name: "Combined Special and Number"
  append: ["123!", "!123", "@123", "123@"]
  description: "Combined number and special character suffixes"

- name: "Month Numbers"
  append: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"]
  description: "Month number suffixes"

- name: "Common Patterns"
  patterns:
    - "{word}123"
    - "{word}!"
    - "{word}@"
    - "{word}#"
    - "@{word}"
    - "#{word}"
    - "{word}{year}"
  description: "Common password patterns"

- name: "Date Patterns"
  patterns:
    - "{word}MMDD"
    - "{word}DDMM"
    - "{word}MMYY"
    - "{word}YYMM"
  description: "Date-based patterns"

- name: "Keyboard Patterns"
  append: ["qwerty", "123456", "abc123"]
  description: "Common keyboard patterns"

- name: "Reversals"
  transform: "reverse"
  description: "Reverse the word"

- name: "Case Alternation"
  transform: "alternate_case"
  description: "Alternate between upper and lower case"

- name: "Double Letters"
  transform: "double_letters"
  description: "Double each letter in the word"

- name: "Common Substitutions"
  substitutions:
    and: "&"
    at: "@"
    to: "2"
    for: "4"
    ate: "8"
    one: "1"
    won: "1"
    too: "2"
    two: "2"
    four: "4"
    eight: "8"
  description: "Common word substitutions"
